apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cronjob.fullname" . }}
  labels:
    app: {{ include "cronjob.name" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  suspend: {{ .Values.suspend }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "cronjob.name" . }}
        spec:
          restartPolicy: "{{.Values.restart}}"
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: OTEL_EXPORTER_OTLP_ENDPOINT
                  value: "http://otelcollector-service.monitoring.svc.cluster.local:4317"
                - name: ENVIRONMENT
                  value: {{ .Values.global.environment }}
                - name: SYSTEM
                  value: {{ .Values.global.system }}
                - name: APPLICATION
                  value: {{ .Values.global.application }}
                - name: DEPLOYABLE_UNIT
                  value: {{ .Values.global.deployable_unit }}
          volumeMounts:
            {{- if .Values.secrets.enabled}}
            - mountPath: app/secrets.yaml
              name: appsecrets
              subPath: secrets
            {{- end}}
            - mountPath: app/appconfig.Production.yaml
              name: appconfig
              subPath: appconfig.Production.yaml
      volumes:
        {{- if .Values.secrets.enabled}}
        - name: appsecrets
          secret:
            secretName: "{{ include "cronjob.fullname" . }}-secrets"
            defaultMode: 420
        {{- end}}
        - name: appconfig
          configMap:
            name: "{{ include "cronjob.fullname" . }}-appconfig" 