# my-react-app/values.yaml


deployment:
  replicaCount: 1
  image:
    repository: 192.168.0.8:5000/personal-website:latest
    tag: latest
    pullPolicy: IfNotPresent

  service:
    name: my-react-app
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    pathType: ImplementationSpecific
    path: /

