# my-react-app/values.yaml


replicaCount: 1
image:
  repository: docker.io/library/personal-website
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: react-app
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  pathType: ImplementationSpecific
  path: /

