# my-deployment/values.yaml

global:
  environment: Production
  system: TestSystem
  application: test-application
  deployableUnit: app

schedule: "*/2 * * * *"
restart: OnFailure
suspend: false
image:
  repository: docker-registry.mw/personal-website
  tag: 0.0.3
  pullPolicy: IfNotPresent

secrets:
  enabled: false


appconfig: {}
