apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: matiwall
  namespace: mw
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`matiaswallenius.com`)
      priority: 10
      services:
        - name: {{ .Values.service.name }}
          port: 80
