# my-deployment/templates/cronjob.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployment.fullname" . }}
  labels:
    app: {{ include "deployment.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "deployment.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "deployment.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcollector-service.monitoring.svc.cluster.local:4317"
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: SYSTEM
              value: {{ .Values.global.system }}
            - name: APPLICATION
              value: {{ .Values.global.application }}
            - name: DEPLOYABLE_UNIT
              value: {{ .Values.global.deployable_unit }}
