# my-deployment/templates/cronjob.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcollector-service.monitoring.svc.cluster.local:4317"
            - name: ENVIRONMENT
              value: {{ .Values.global.environment }}
            - name: SYSTEM
              value: {{ .Values.global.system }}
            - name: APPLICATION
              value: {{ .Values.global.application }}
            - name: DEPLOYABLE_UNIT
              value: {{ .Values.global.deployableUnit }}
          volumeMounts:
            {{- if .Values.secrets.enabled}}
            - mountPath: app/secrets.yaml
              name: appsecrets
              subPath: secrets
            {{- end}}
            - mountPath: app/appconfig.Production.yaml
              name: appconfig
              subPath: appconfig.Production.yaml
      volumes:
        {{- if .Values.secrets.enabled }}
        - name: appsecrets
          secret:
            secretName: "{{ include "common.fullname" . }}-secrets"
            defaultMode: 420
        {{- end }}
        - name: appconfig
          configMap:
            name: "{{ include "common.fullname" . }}-appconfig" 
