apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "common.fullname" . }}-ingress-route"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      priority: {{ .Values.ingress.priority }}
      services:
        - name: {{ .Values.service.name }}
          port: 80