apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "deployment.fullname" . }}-ingress-route"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.path }}`)
      priority: 10
      services:
        - name: {{ .Values.service.name }}
          port: 80
      middlewares:
        - name: "{{ include "deployment.fullname" . }}-ingress-route-pathprefixstrip"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: "{{ include "deployment.fullname" . }}-ingress-route-pathprefixstrip"
spec:
  stripPrefix:
    prefixes:
      - "{{ .Values.ingress.path }}"