apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "deployment.fullname" . }}-ingress-route"
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.url }}`)
      priority: 10
      services:
        - name: {{ .Values.service.name }}
          port: 80
