{{- if .Values.secrets.enables }}
apiVersion: vaultproject.io/v1alpha1
kind: VaultSecret
metadata:
  name: "{{ .Chart.name }}-secrets"
spec: 
  keys:
    - secrets
  {{- if .Values.secrets.path }}
  path: {{ .Values.secrets.path}}
  {{- else-}}
  path: "kv/{{ .Values.global.system }}/{{ .Values.global.environment }}/{{ .Values.global.application }}/{{ .Chart.name }}"
  {{- end }}
  {{- if .Values.secrets.version}}
  version: {{ .Values.secrets.version}}
  {{- end }}
  type: Opaque
{{- end}}