{{- if .Values.secrets.enabled }}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "{{ .Chart.Name }}-secrets"
spec: 
  keys:
    - secrets
  {{- if .Values.secrets.path }}
  path: {{ .Values.secrets.path}}
  {{- else }}
  path: "kv/{{ .Values.global.system }}/{{ .Values.global.environment }}/{{ .Values.global.application }}/{{ .Values.global.deployableUnit }}"
  {{- end }}
  {{- if .Values.secrets.version}}
  version: {{ .Values.secrets.version}}
  {{- end }}
  type: Opaque
{{- end}}